### ISSUE TITLE
Is this branch still prefered over bugfix-2.0.x?

### ISSUE THREAD

**Issue by DavidWAbrahams** [LVD-AC/Marlin-AC#35]
Sorry to contact you via bug, but I couldn't find another way.

I saw your most recent contributions were submitted to MarlinFirmware/bugfix-2.0.x rather than this fork. So if I want the latest features on an FLSun kossel can I switch to bugfix-2.0 or should I stay on Marlin-AC?

Thanks for your work!

**Comment by LVD-AC** [comment]
Bugfix-2.0 was trailing behind (as usual) but finally is now in sync with Marlin-AC. At this stage Marlin-AC, 1.1.9 and bugfix-2.0 have the same features regarding calibration.

**Comment by DavidWAbrahams** [comment]
Cool, thanks!
